name: Keep Project Alive 15

on:
  push:
    branches:
      - main  # این باعث میشه هر بار که تغییری در branch اصلی push بشه، workflow اجرا بشه
  schedule:
    - cron: '*/15 * * * *'  # این باعث میشه هر 10 دقیقه یک بار اجرا بشه

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping project URL
        run: curl -s https://abaft-absorbing-seagull.glitch.me > /dev/null  # URL پروژه‌ات رو وارد کن
