name: Keep Project Alive

on:
  push:
    branches:
      - main  # این باعث میشه هر بار که تغییری در branch اصلی push بشه، workflow اجرا بشه
  schedule:
    - cron: '*/2 * * * *'  # این خط باعث میشه هر 5 دقیقه یک بار اجرا بشه

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping project URL
        run: curl -s https://abaft-absorbing-seagull.glitch.me > /dev/null  # URL پروژه‌ات رو وارد کن
